[package]
name = "ccip_message_receiver"
edition = "2024"

[dependencies]
ccip = { git = "https://github.com/smartcontractkit/chainlink-sui.git", subdir = "contracts/ccip/ccip", rev = "1239126e21ed0257fa190aa87893f14730ef7e04" }
